export const nagararaftlocations = [
  {
    nagaraid: 1,
    nagaraimg: require('../../assets/images/nagaraloc1.png'),
    nagaradiffimg: require('../../assets/images/nagaramed.png'),
    nagaratitle: 'French Broad River – Section 9',
    nagaralat: 35.4631,
    nagaralon: -82.7124,
    nagaradiff: 'Medium',
    nagaraarticle: `Flowing through steep forested ridges, Section 9 of the French Broad is Asheville’s classic rafting route. Rapids are fast but predictable, with long calm stretches perfect for beginners stepping into mountain water for the first time. The view constantly changes — sandstone cliffs, hanging vines, and the faint smell of pine after rain. It’s where most locals learn to read the current and trust the flow.`,
  },
  {
    nagaraid: 2,
    nagaraimg: require('../../assets/images/nagaraloc2.png'),
    nagaradiffimg: require('../../assets/images/nagaradiff.png'),
    nagaratitle: 'Pigeon River – Upper Run',
    nagaralat: 35.759,
    nagaralon: -83.1069,
    nagaradiff: 'Hard',
    nagaraarticle: `Fed by the Smoky Mountains, this river is all pulse and thunder. Narrow rock corridors and quick drops make every turn a rush of cold spray and laughter. Professional guides often bring small groups here for training sessions — it’s wild, but never chaotic. The air smells of mist and wet granite; the sound of rushing water echoes for miles.`,
  },
  {
    nagaraid: 3,
    nagaraimg: require('../../assets/images/nagaraloc3.png'),
    nagaradiffimg: require('../../assets/images/nagaramed.png'),
    nagaratitle: 'Nantahala River',
    nagaralat: 35.3343,
    nagaralon: -83.6336,
    nagaradiff: 'Medium',
    nagaraarticle: `The Nantahala is pure mountain energy — cool, crystal-clear, and perfectly paced. It winds through lush gorges with mossy rocks and swinging bridges above. Calm pools follow quick bursts of whitewater, creating a rhythm that feels like music. Ideal for mid-level rafters looking for both challenge and scenery.`,
  },
  {
    nagaraid: 4,
    nagaraimg: require('../../assets/images/nagaraloc4.png'),
    nagaradiffimg: require('../../assets/images/nagaradiff.png'),
    nagaratitle: 'Green River – The Narrows',
    nagaralat: 35.2615,
    nagaralon: -82.3098,
    nagaradiff: 'Expert',
    nagaraarticle: `Hidden deep in a gorge, the Narrows is one of North Carolina’s most technical whitewater routes. Sharp turns and vertical drops carve through emerald-green cliffs. Few attempt the full run, but watching the water here is a spectacle — it’s the untamed heart of the Blue Ridge. A place where adrenaline meets silence.`,
  },
  {
    nagaraid: 5,
    nagaraimg: require('../../assets/images/nagaraloc5.png'),
    nagaradiffimg: require('../../assets/images/nagaraeasy.png'),
    nagaratitle: 'Tuckasegee River',
    nagaralat: 35.3735,
    nagaralon: -83.2077,
    nagaradiff: 'Easy',
    nagaraarticle: `A family favorite, calm and bright under open sky. The Tuckasegee meanders through farms and foothills, where herons stand still in the shallows. It’s gentle but not dull — every bend reveals a new mountain reflection, and locals say you can smell the wildflowers before you see them.`,
  },
  {
    nagaraid: 6,
    nagaraimg: require('../../assets/images/nagaraloc6.png'),
    nagaradiffimg: require('../../assets/images/nagaradiff.png'),
    nagaratitle: 'Nolichucky River',
    nagaralat: 36.0484,
    nagaralon: -82.4467,
    nagaradiff: 'Hard',
    nagaraarticle: `A border river cutting between North Carolina and Tennessee, the Nolichucky roars through a deep canyon. Rapids like Quarter Mile and Jaws demand precision. For advanced rafters, this is a legend — wild, remote, and unforgettable. The steep gorge walls rise hundreds of feet, glowing orange in the afternoon sun.`,
  },
  {
    nagaraid: 7,
    nagaraimg: require('../../assets/images/nagaraloc7.png'),
    nagaradiffimg: require('../../assets/images/nagaradiff.png'),
    nagaratitle: 'Wilson Creek',
    nagaralat: 35.9929,
    nagaralon: -81.793,
    nagaradiff: 'Hard',
    nagaraarticle: `Wilson Creek is pure wilderness. Small, powerful, and fast, it rushes over boulders framed by old-growth forest. It’s not long, but it’s intense — rafters describe it as “ten minutes that feel like a lifetime.” Perfect for short adrenaline runs and photography.`,
  },
  {
    nagaraid: 8,
    nagaraimg: require('../../assets/images/nagaraloc8.png'),
    nagaradiffimg: require('../../assets/images/nagaraeasy.png'),
    nagaratitle: 'Davidson River',
    nagaralat: 35.2814,
    nagaralon: -82.7147,
    nagaradiff: 'Easy',
    nagaraarticle: `The Davidson flows quietly through Pisgah National Forest — a river of calm reflections and golden sunlight through the trees. It’s ideal for solo paddling or a slow afternoon drift. Locals often say it’s the perfect place to clear your head after harder rides.`,
  },
  {
    nagaraid: 9,
    nagaraimg: require('../../assets/images/nagaraloc9.png'),
    nagaradiffimg: require('../../assets/images/nagaramed.png'),
    nagaratitle: 'Big Laurel Creek',
    nagaralat: 35.915,
    nagaralon: -82.7774,
    nagaradiff: 'Medium',
    nagaraarticle: `Tucked away north of Asheville, Big Laurel offers a steady mix of technical water and forest serenity. Expect cold splashes, mossy stones, and the occasional deer on the bank. This creek teaches rhythm — every curve is different, but it all flows naturally.`,
  },
  {
    nagaraid: 10,
    nagaraimg: require('../../assets/images/nagaraloc10.png'),
    nagaradiffimg: require('../../assets/images/nagaraeasy.png'),
    nagaratitle: 'South Toe River',
    nagaralat: 35.8454,
    nagaralon: -82.2711,
    nagaradiff: 'Easy',
    nagaraarticle: `A hidden gem beneath Mount Mitchell. The South Toe feels untouched — shallow in places, but lined with smooth stones and mountain laurel. Perfect for meditative floats or quick morning rides. It’s the kind of river that reminds you why you fell in love with rafting in the first place.`,
  },
];
